In [2]:
import torch
import numpy as np

In [8]:
# create a tensor directly with data
print('create a tensor directly with data')
data = [[1, 2], [3,4]]
print(data)
x_data = torch.tensor(data)
print(x_data)

create a tensor directly with data
[[1, 2], [3, 4]]
tensor([[1, 2],
        [3, 4]])


In [4]:
# create a tensor with numpy array
print('create a tensor with numpy array')
np_array = np.array(data)
print(np_array)
x_np = torch.from_numpy(np_array)
print(x_np)

create a tensor with numpy array
[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])


In [11]:
# create tensors with another tensor
print('create a tensor with another tensor')
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"rand Tensor: \n {x_rand} \n")

create a tensor with another tensor
Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

rand Tensor: 
 tensor([[0.3609, 0.2664],
        [0.8784, 0.4243]]) 



In [17]:
# create tensors with random or constant value
print('create tensors with random or constant value')
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Rand Tensor: \n {rand_tensor}\n")
print(f"Ones Tensor: \n {ones_tensor}\n")
print(f"Zeros Tensor: \n {zeros_tensor}\n")

create tensors with random or constant value
Rand Tensor: 
 tensor([[0.9840, 0.4366, 0.5297],
        [0.1384, 0.5081, 0.4485]])

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])



In [3]:
# attributes of tensor
print('attributes of tensor')
tensor = torch.rand(3,4)

print(f'Shape of tensor: {tensor.shape}')
print(f'Datatype of tensor: {tensor.dtype}')
print(f'Device tensor is stored on: {tensor.device}')

if torch.cuda.is_available():
    tensor = tensor.to("cuda")
    print(f'tensor is moved to GPU')
    print(f'Device tensor is stored on: {tensor.device}')

attributes of tensor
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [ ]:
# indexing and slicing of tensor
print('indexing and slicing of tensor')
tensor = torch.rand(4, 4)
print(f'Tensor is: {tensor}')
print(f'Firt row: {tensor[0]}')
print(f'Firt column: {tensor[:, 0]}')
print(f'Last column: {tensor[..., -1]}')
tensor[:, -1] = 0
print(print(f'Tensor is: {tensor}'))

Tensor is: tensor([[0.4536, 0.0291, 0.4900, 0.3723],
        [0.1609, 0.8136, 0.6747, 0.2066],
        [0.4043, 0.7335, 0.8080, 0.9356],
        [0.5692, 0.0753, 0.8906, 0.1370]])
Firt row: tensor([0.4536, 0.0291, 0.4900, 0.3723])
Firt column: tensor([0.4536, 0.1609, 0.4043, 0.5692])
Last column: tensor([0.3723, 0.2066, 0.9356, 0.1370])
Tensor is: tensor([[0.4536, 0.0291, 0.4900, 0.0000],
        [0.1609, 0.8136, 0.6747, 0.0000],
        [0.4043, 0.7335, 0.8080, 0.0000],
        [0.5692, 0.0753, 0.8906, 0.0000]])
None


In [10]:
# arithmetic operations
print('arithmetic operations')
tensor = torch.rand(4, 4)
print(f'Tensor is: {tensor}')
y1 = tensor @ tensor.T
print(f'matrix mulplication with @ : {y1}')
y2 = tensor.matmul(tensor.T)
print(f'matrix mulplication with tensor.matmul() : {y2}')
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)
print(f'matrix mulplication with torch.matmul() : {y3}')

z1 = tensor * tensor
print(f'element-wise product with * : {z1}')
z2 = tensor.mul(tensor)
print(f'element-wise product with tensor.mul() : {z2}')
z3 = torch.rand_like(z1)
torch.mul(tensor, tensor, out=z3)
print(f'element-wise product with torch.mul() : {z3}')

arithmetic operations
Tensor is: tensor([[0.8569, 0.3624, 0.0272, 0.1688],
        [0.1341, 0.9611, 0.1737, 0.5484],
        [0.0658, 0.8909, 0.2267, 0.8765],
        [0.8602, 0.6679, 0.5453, 0.5119]])
matrix mulplication with @ : tensor([[0.8949, 0.5604, 0.5333, 1.0804],
        [0.5604, 1.2725, 1.3850, 1.1327],
        [0.5333, 1.3850, 1.6176, 1.2239],
        [1.0804, 1.1327, 1.2239, 1.7454]])
matrix mulplication with tensor.matmul() : tensor([[0.8949, 0.5604, 0.5333, 1.0804],
        [0.5604, 1.2725, 1.3850, 1.1327],
        [0.5333, 1.3850, 1.6176, 1.2239],
        [1.0804, 1.1327, 1.2239, 1.7454]])
matrix mulplication with torch.matmul() : tensor([[0.8949, 0.5604, 0.5333, 1.0804],
        [0.5604, 1.2725, 1.3850, 1.1327],
        [0.5333, 1.3850, 1.6176, 1.2239],
        [1.0804, 1.1327, 1.2239, 1.7454]])
element-wise product with * : tensor([[7.3432e-01, 1.3132e-01, 7.3983e-04, 2.8487e-02],
        [1.7975e-02, 9.2367e-01, 3.0185e-02, 3.0070e-01],
        [4.3294e-03, 7.9363e-01

In [ ]:
# single element
print('single element')
agg = tensor.sum()
print(f'tensor.sum() is {agg}')
print(f'tensor.sum() type is {type(agg)}')
print(f'tensor.sum() shape is {agg.shape}')
print(f'tensor.sum() shape is {agg.dtype}')

agg_item = agg.item()
print(f'tensor aggregation is {agg_item}')
print(f'tensor aggregation type is {type(agg_item)}')


single element
tensor.sum() is 7.877677917480469
tensor.sum() type is <class 'torch.Tensor'>
tensor.sum() shape is torch.Size([])
tensor.sum() shape is torch.float32
tensor aggregation is 7.877677917480469
tensor aggregation type is <class 'float'>


In [15]:
# in-place operation
print('in-place operation')

print(tensor)
tensor.add_(5)
print(tensor)

in-place operation
tensor([[0.8569, 0.3624, 0.0272, 0.1688],
        [0.1341, 0.9611, 0.1737, 0.5484],
        [0.0658, 0.8909, 0.2267, 0.8765],
        [0.8602, 0.6679, 0.5453, 0.5119]])
tensor([[5.8569, 5.3624, 5.0272, 5.1688],
        [5.1341, 5.9611, 5.1737, 5.5484],
        [5.0658, 5.8909, 5.2267, 5.8765],
        [5.8602, 5.6679, 5.5453, 5.5119]])


In [3]:
# shared memory between tensor and numpy array
print('shared memory between torch and numpy')

t = torch.ones(5)
print(f'tensor is {t}')
n = t.numpy()
print(f'numpy is {n}')

print('tensor adds 5')
t.add_(5)
print(f'tensor is {t}')
print(f'numpy is {n}')

np.add(n, 5, out=n)
print('numpy adds 5')
print(f'tensor is {t}')
print(f'numpy is {n}')

shared memory between torch and numpy
tensor is tensor([1., 1., 1., 1., 1.])
numpy is [1. 1. 1. 1. 1.]
tensor adds 5
tensor is tensor([6., 6., 6., 6., 6.])
numpy is [6. 6. 6. 6. 6.]
numpy adds 5
tensor is tensor([11., 11., 11., 11., 11.])
numpy is [11. 11. 11. 11. 11.]


In [7]:
# transform numpy array to tensor
print('transform numpy array to tensor')

n = np.ones(5)
t = torch.from_numpy(n)

print(f'tensor is {t}')
print(f'numpy is {n}')

print('tensor adds 5')
t.add_(5)
print(f'tensor is {t}')
print(f'numpy is {n}')

np.add(n, 5, out=n)
print('numpy adds 5')
print(f'tensor is {t}')
print(f'numpy is {n}')

transform numpy array to tensor
tensor is tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
numpy is [1. 1. 1. 1. 1.]
tensor adds 5
tensor is tensor([6., 6., 6., 6., 6.], dtype=torch.float64)
numpy is [6. 6. 6. 6. 6.]
numpy adds 5
tensor is tensor([11., 11., 11., 11., 11.], dtype=torch.float64)
numpy is [11. 11. 11. 11. 11.]
